### ISSUE TITLE
Make base_url a config value

### ISSUE THREAD

**Issue by jdillard** [jdillard/sphinx-sitemap#1]
`base_url` needs to be a config value, it is currently hard coded.

**Comment by FabriceSalvaire** [comment]
Seems to work fine excepted it requires this fix

`sed -e 's/http:\/\/my-site.com\/docs/https:\/\/XXXX/' -i ${sitemap}`

Would be cool to fix it and push it to Pypi

**Comment by jdillard** [comment]
> Would be cool to fix it and push it to Pypi

That was the original plan, I'll look at revisiting that once I merge your fix.

**Comment by jdillard** [comment]
Fixed in #5

**Comment by jdillard** [comment]
@FabriceSalvaire sphinx_sitemap now on PyPI and I have installed it successfully.
