### ISSUE TITLE
PyPI build doesn't seem to have latest version

### ISSUE THREAD

**Issue by remyabel** [jdillard/sphinx-sitemap#16]
I installed your extension using `pip install --user sphinx-sitemap`. `version.py` is updated but not `__init__.py`. See this diff:

```diff
diff ~/.local/lib/python2.7/site-packages/sphinx_sitemap/__init__.py __init__.py

19c19
<     """Setup conntects events to the sitemap builder"""
---
>     """Setup connects events to the sitemap builder"""
22c22
<         default='https://my-site.com/docs/',
---
>         default=None,
```
, etc.

**Comment by jdillard** [comment]
I'm ramping up for the next version. Those changes in master are mostly refactoring right now, but I am hoping to merge #15 soon as I have a multi-lingual project I am working on, so I'll be able to test it out first hand. I plan to cut a new release when I feel that is stable enough.
