### ISSUE TITLE
Add the ability for exclusions

### ISSUE THREAD

**Issue by jdillard** [jdillard/sphinx-sitemap#2]
Whether through a config value array, `sitemap_exclude`, and/or metadata on the page, `:nositemap:`, to be excluded.

**Comment by msbt** [comment]
Hey @jdillard, awesome work on the extension, any chance that the `sitemap_exclude` feature is still somewhere on the roadmap?

**Comment by jdillard** [comment]
I can try and make an attempt at it "soon", but no promises. Were you thinking something like this would work for you?

```
sitemap_excludes = [
    "/path/to/page1.rst",
    "/path/to/page2.rst",
]
```

**Comment by msbt** [comment]
Thanks for the quick reply! In theory yes, but for my use-case it's more about the `search.html` and `genindex.html` which are basically empty and recognized as soft 404s by search engines, so I would target system pages instead of rendered `.rst`s

**Comment by kryskool** [comment]
Hi @msbt for sphinx basic theme and furo, the meta robot have no index value.

* [basic theme](https://github.com/sphinx-doc/sphinx/commit/71d3eaee752f0843b87b4a2c4d8cf5d5ae7a2ecd)
* [furo](https://github.com/pradyunsg/furo/commit/035b27651632e20fec2277e7398cdd00dc63a73f)

**Comment by msbt** [comment]
@kryskool thanks, but I'd rather not have it in the sitemap in the first place, this piles up the "discovered but not indexed" pages in various analytics tools.

**Comment by jdillard** [comment]
@msbt How does this PR look? https://github.com/jdillard/sphinx-sitemap/pull/91

**Comment by msbt** [comment]
@jdillard oh wow, thanks so much for the addition and quick implementation, appreciate it a lot! PR looks great, exactly how I imagined it would work!
