### ISSUE TITLE
Add option to remove file extension from output url's

### ISSUE THREAD

**Issue by christopherpickering** [jdillard/sphinx-sitemap#31]
Hi, thanks for this!

How about an option to remove the ".html" from the output urls? For example, using netlify you can server urls w/out the ".html" on the end.. looking nicer.

**Comment by humitos** [comment]
I'd assume that this should respect the Sphinx builder that you are using: html or dirhtml builder.

**Comment by christopherpickering** [comment]
Oh nice, I hadn't seen that option before and will give it a shot. Looks like it should work.

**Comment by jdillard** [comment]
Closing this as that should be the solution (`.html` isn't hardcoded in the extensions's logic), but can reopen if that doesn't work.

**Comment by christopherpickering** [comment]
Thanks, this worked well.

**Comment by czue** [comment]
Since I've now had this problem twice and forgotten the answer both times, the way to switch is to run:
```
make dirhtml
```

Instead of
```
make html
````
