### ISSUE TITLE
html_file_suffix configuration values is not respected

### ISSUE THREAD

**Issue by jdetaeye** [jdillard/sphinx-sitemap#56]
In my conf.py file I set "html_file_suffix=.php".
The generated sitemap however refers to URLs with the extension ".html".

I believe it's hardcoded at https://github.com/jdillard/sphinx-sitemap/blob/edf8c48339b6fe56ed2738298303e4ca4b997970/sphinx_sitemap/__init__.py#L109

Shall I create a pull request?

**Comment by jdillard** [comment]
Ah, I didn't know about that configuration option. That would be great!

**Comment by jdillard** [comment]
[Version 2.5.0](https://github.com/jdillard/sphinx-sitemap/releases/tag/v2.5.0) with support for `html_file_suffix` has now been released, thanks for the PR!
