### ISSUE TITLE
loading pickled environment is failed, possibly because using `multiprocessing.Manager`

### ISSUE THREAD

**Issue by thawatchai** [jdillard/sphinx-sitemap#67]
I initially reported this issue in the sphinx-doc repository (https://github.com/sphinx-doc/sphinx/issues/11463), but upon further investigation, I've come to realize that the error might stem from an extension. I've narrowed down the culprit to `sphinx-sitemap`, which utilizes `multiprocessing.Manager`.

It appears that the code leveraging `multiprocessing.Manager` cannot be pickled.

Any insights or solutions would be greatly appreciated. Thank you!

**Comment by jdillard** [comment]
The latest release (2.5.1) should have the fix for that: https://github.com/jdillard/sphinx-sitemap/releases/tag/v2.5.1
