### ISSUE TITLE
Error with Sphinx 7.2

### ISSUE THREAD

**Issue by kai687** [jdillard/sphinx-sitemap#69]
`app.outdir` is now a Path, not a string,
so [line 213](https://github.com/jdillard/sphinx-sitemap/blob/3bd87ef166bc9f3758d360ad4d23b524668b161d/sphinx_sitemap/__init__.py#L213) breaks.

**Comment by larsoner** [comment]
Opened https://github.com/jdillard/sphinx-sitemap/pull/70, hopefully it works :crossed_fingers:

**Comment by jdillard** [comment]
Thanks! I'll have to test it out to make sure it doesn't break for older versions (it doesn't seem to be) and update tox as well now that 7 is out.

**Comment by larsoner** [comment]
> I'll have to test it out to make sure it doesn't break for older versions (it doesn't seem to be) and update tox as well now that 7 is out.

Want me to add that parametrization to `continuous_integration.yml`? Then you don't have to manually test this...

**Comment by larsoner** [comment]
... couldn't resist the temptation. Added to #70 but I can revert if needed

**Comment by jdillard** [comment]
Thanks for pointing that out @kai687 and thanks for the great work in the PR @larsoner!

2.5.1 is out now with the fix: https://github.com/jdillard/sphinx-sitemap/releases/tag/v2.5.1
